		       #######################
		       ### Hyprland Config ###
		       #######################

#		-----         COLORS           -----
#
# 	Color Variablesn
# Wiki: https://wiki.hypr.land/Configuring/Variables/
source = ~/.config/hypr/modules/colors.conf

#		-----        PROGRAMS	       -----
#
# 	programs variables and autostart apps
# Wiki: https://wiki.hypr.land/Configuring/Keywords/
source = ~/.config/hypr/modules/programs.conf

#		-----  	  LOOK AND FEEL        -----
#
# 	gaps,borders,rounding,shadow,etc.
# Wiki: https://wiki.hypr.land/Configuring/Variables/#decoration
source = ~/.config/hypr/modules/LookAndFeel.conf

#		-----  WINDOWS AND WORKSPACES  -----
# 
# 	windowrules
# Wiki: https://wiki.hypr.land/Configuring/Window-Rules/
# Wiki: https://wiki.hypr.land/Configuring/Workspace-Rules/
source = ~/.config/hypr/modules/WindowsAndWorkspaces.conf

# 		----        ANIMATIONS         -----
#
#	animations setting
# Wiki: https://wiki.hypr.land/Configuring/Animations/
source = ~/.config/hypr/modules/animations.conf

#		----- 	       INPUT 	       -----
#
# 	keyboard layout and touchpad gestures
# Wiki: https://wiki.hypr.land/Configuring/Variables/#input
source = ~/.config/hypr/modules/input.conf

#		-----       KEYBINDINGS        -----
#
#	set keybinds
# Wiki: https://wiki.hypr.land/Configuring/Binds/
source = ~/.config/hypr/modules/keybinds.conf

#		-----         MONITORS         -----
#
# 	monitors configuration
# Wiki: https://wiki.hypr.land/Configuring/Monitors/
source = ~/.config/hypr/modules/monitors.conf

#		-----   ENVIRONMENT VARIABLES  -----
# 
# 	cursor size
# Wiki: https://wiki.hypr.land/Configuring/Environment-variables/
source = ~/.config/hypr/modules/environmentVariables.conf

#		-----       PERMISSIONS        -----
#
#	hyprland permissions settings
# Wiki: https://wiki.hypr.land/Configuring/Permissions/
source = ~/.config/hypr/modules/permissions.conf


no_donation_nag = true
disable_splash_rendering = true


           #cursor {
           #    no_hardware_cursors = true
           #}
