$active = ~/.config/Wallpapers/etheralbath.png

wallpaper {
	monitor = eDP-1
	path = $active
	fit_mode = cover
}

wallpaper {
	monitor =
	path = $active
	fit_mode = cover
}

splash = false

ipc = true
