		#############################
		### ENVIRONMENT VARIABLES ###
		#############################


env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
    #env = GBM_BACKEND,nvidia-drm

env = WLR_DRM_DEVICES,$HOME/.config/hyprGPU/card:$HOME/.config/hyprGPU/cardInt
