		################
		### MONITORS ###
		################
#AOC 279194
monitor=desc:AOC 27G1G4 0x00026952, 1920x1080@144.00101, -1920x0, 1

#nitro laptop 
monitor=desc:Chimei Innolux Corporation 0x1521, 1920x1080@144.00301, 0x0, 1.2

#laptop Monitor
    #monitor=eDP-1, 1366x768@60, 0x0, 1


cursor {
    no_hardware_cursors = true
}
#random monitors
    #monitor=,preffered,auto-right,1

