		############################
		### PROGRAMS & AUTOSTART ###
		############################



# Variables
$terminal = kitty
$fileManager = kitty yazi
$menu = rofi -show drun
$browser = zen-browser

# Autostart
exec-once = hyprpaper
exec-once = waybar
exec-once = udiskie
exec-once = wl-paste --watch cliphist store
exec-once = mako
